asfxgf/ProxyRungis

config/environments/production.rb

ssl certificate

---

.gitignore
Gemfile
Gemfile.lock
app/models/package.rb
app/uploaders/photo_uploader.rb
db/migrate/20190826155249_add_photo_to_packages.rb
db/schema.rb
db/seeds.rb

seed created

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss
app/controllers/packages_controller.rb
app/views/packages/index.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb
db/migrate/20190826155249_add_photo_to_packages.rb

Homepageliaisons

---

app/controllers/orders_controller.rb
app/models/order.rb
app/views/layouts/application.html.erb
app/views/orders/index.html.erb
config/routes.rb
test/controllers/orders_controller_test.rb

updating order page without map
changing the name from "TODO" to "ProxyRungis"
creating order controller and view

page without map

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_order.scss
app/controllers/orders_controller.rb
app/views/orders/index.html.erb

Orders page map

---

app/assets/stylesheets/pages/_index-packages.scss
app/views/packages/index.html.erb

Ok ici on a modifié des trucs pour que les cards s'affichent correctement. Il faudra plus tard les aggrandir, rajouer un container, creer un display flex + align la BILL avec la Cards-list.

some bugs fixed en relation avec les cartes et leur affichage

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_show-packages.scss
app/assets/stylesheets/pages/_index-packages.scss
app/controllers/packages_controller.rb
app/models/cart_item.rb
app/views/packages/index.html.erb
app/views/packages/show.html.erb

Packages index changes:
- place for the user cart
- modal available from a button inside every card

Cart items view

---

.gitignore
app/assets/stylesheets/pages/_order.scss
app/views/orders/index.html.erb

Create resto controller

---

app/controllers/restaurants_controller.rb
app/models/restaurant.rb
config/routes.rb

creating restaurant controller
udpdating validations in restaurant model about end/start hour
creating restaurant routes "resources"

controller restaurant

---

app/views/orders/show.html.erb
app/views/payments/new.html.erb

ici c'est le gros recap des familles

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_show-packages.scss
app/controllers/cart_items_controller.rb
app/views/cart_items/_form.html.erb
app/views/packages/index.html.erb

Front packages index

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/pages/_order.scss
app/views/layouts/application.html.erb
app/views/shared/_footer.html.erb

Front details

---

app/controllers/carts_controller.rb
app/controllers/pages_controller.rb

on a debug 1 feature

---

app/assets/stylesheets/components/_map.scss
app/controllers/payments_controller.rb
app/javascript/plugins/init_mapbox.js
app/models/order.rb
app/views/orders/edit.html.erb
app/views/payments/_info_order_window.html.erb
app/views/payments/_info_window.html.erb
app/views/payments/new.html.erb

map created on the payment page

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_cart.scss
app/assets/stylesheets/components/_show-packages.scss
app/controllers/cart_items_controller.rb
app/views/cart_items/destroy.js.erb
app/views/packages/index.html.erb

Display cart as modal

---

app/assets/stylesheets/pages/_dashboard.scss
app/assets/stylesheets/pages/_index.scss
app/controllers/pages_controller.rb
app/views/orders/show.html.erb
app/views/pages/dashboard.html.erb
app/views/pages/home.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb
test/controllers/dashboard_controller_test.rb
test/controllers/users_controller_test.rb

Création DashBoard
Implémentation "mes commandes" dans la navbar"
CSS et HTML dashboard sans balises ERB donc pas encore dynamique

Disable button

---

app/assets/stylesheets/pages/_dashboard.scss
app/views/pages/dashboard.html.erb

Ici j'ai ajouté tous les champs dinamiques du dashboard, j'ai également réoganisé le css file du dashboard, les cartes sont trop grosses elles sont a modifié, il y a un display flex a faire pour aligner les cards 2 par 2 ou 3 par 3. Il faut également regarder pour le format de Day car le strift.time rend une date en Anglais. Je suis perssuadé qu'on peux faire un split sur l'adresse de manière à ce que seul la rue soit affichée et non le code postal + ville.

Dashboard update

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_cart.scss
app/assets/stylesheets/components/_map.scss
app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/pages/_dashboard.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_order.scss
app/views/payments/new.html.erb
app/views/shared/_navbar.html.erb

changes in css

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/pages/_edit.scss
app/assets/stylesheets/pages/_index.scss
app/javascript/packs/application.js
app/javascript/plugins/flatpickr.js
app/views/orders/edit.html.erb

Modify form

---

public/404.html
public/500.html

modif des 2 pages d'erreurs
